;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-beginner-reader.ss" "lang")((modname |080 - Struct-Templates|) (read-case-sensitive #t) (teachpacks ((lib "image.rkt" "teachpack" "2htdp") (lib "universe.rkt" "teachpack" "2htdp") (lib "testing.rkt" "teachpack" "htdp") (lib "batch-io.rkt" "teachpack" "2htdp") (lib "web-io.rkt" "teachpack" "2htdp"))) (htdp-settings #(#t constructor repeating-decimal #f #t none #f ((lib "image.rkt" "teachpack" "2htdp") (lib "universe.rkt" "teachpack" "2htdp") (lib "testing.rkt" "teachpack" "htdp") (lib "batch-io.rkt" "teachpack" "2htdp") (lib "web-io.rkt" "teachpack" "2htdp")) #f)))


;Create templates for functions that consume instances of the following structure types:

(define-struct movie [title director year])
;...
(define (movie-entry m)
  (... (movie-title m) ....
       (movie-director m) ...
       (movie-year m) ...))


(define-struct pet [name number])
;...
(define (pet-entry p)
  ( ...
    (pet-name p) ...
    (pet-number p) ...))


(define-struct CD [artist title price])
;...
(define (CD-entry c)
  ( ...
   (CD-artist c) ...
   (CD-title c) ...
   (CD-price c) ...))


(define-struct sweater [material size color])
;...
(define (sweater-entry s)
  (...
   (sweater-mateerial s) ...
   (sweater-size s) ...
   (sweater-color s) ...))
